services:
  llama-compute-node0:
    image: woodhouse:5000/woodhouse-llama:3.0.0
    container_name: llama-compute-node0   ## Main compute node
    restart: unless-stopped
    volumes:
      - /ai-models:/app/models:ro
      - /sys/devices/system/node:/sys/devices/system/node
    #  - /mnt/ramdisk/sockets:/tmp/sockets
    environment:
      FUNCTION: compute
      RPC_HOST: 127.0.0.1 #/tmp/sockets/rpc0.sock
      RPC_PORT: 50052
      RPC_CACHE: true
      NUM_THREADS: 12
      NUMA_NODE: 0
    security_opt:
      - label:disable
      - seccomp:unconfined
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
      - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cpuset: "0,2,4,6,8,10,12,14,16,18,20,22"
    deploy:
      resources:
        limits:
          memory: 15G
        reservations:
          memory: 12G
    network_mode: host
    healthcheck:
      # Pings the port to ensure the RPC listener is active
      # test: ["CMD-SHELL", "[ -S /tmp/sockets/rpc1.sock ]"]
      test: ["CMD-SHELL", "bash -c 'exec 6<> /dev/tcp/localhost/50052'"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  llama-compute-node1:
    image: woodhouse:5000/woodhouse-llama:3.0.0
    container_name: llama-compute-node1   ## Main compute node
    restart: unless-stopped
    volumes:
      - /ai-models:/app/models:ro
      - /sys/devices/system/node:/sys/devices/system/node
    #  - /mnt/ramdisk/sockets:/tmp/sockets
    environment:
      FUNCTION: compute
      RPC_HOST: 127.0.0.1 # /tmp/sockets/rpc1.sock
      RPC_PORT: 50053
      RPC_CACHE: true
      NUM_THREADS: 12
      NUMA_NODE: 1
    security_opt:
      - label:disable
      - seccomp:unconfined
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
      - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cpuset: "1,3,5,7,9,11,13,15,17,19,21,23"
    deploy:
      resources:
        limits:
          memory: 15G
        reservations:
          memory: 12G
    network_mode: host
    healthcheck:
      # Pings the port to ensure the RPC listener is active
      # test: ["CMD-SHELL", "[ -S /tmp/sockets/rpc1.sock ]"]
      test: ["CMD-SHELL", "bash -c 'exec 6<> /dev/tcp/localhost/50053'"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  llama-frontend:
    image: woodhouse:5000/woodhouse-llama:3.0.0
    container_name: llama-frontend    ## RPC Coordinator and frontend
    restart: unless-stopped
    volumes:
      - /ai-models:/app/models:ro
      - /mnt/ramdisk/sockets:/tmp/sockets
    environment:
      FUNCTION: frontend
      MODEL_PATH: /app/models/Qwen3.5-9B-Uncensored-HauhauCS-Aggressive-Q8_0.gguf
      MODEL_CHAT_TEMPLATE:
      CACHE_TYPE_K: bf16
      CACHE_TYPE_V: bf16
      RPC_SERVER: 127.0.0.1:50052,127.0.0.1:50053,asushouse:50052
      # RPC_SERVERS: /tmp/sockets/rpc0.sock,/tmp/sockets/rpc1.sock,asushouse:50052
      WEB_HOST: 0.0.0.0
      WEB_PORT: 8734
      NUM_THREADS: 4
    security_opt:
      - label:disable
      - seccomp:unconfined
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
      - IPC_LOCK
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 4G
        reservations:
          cpus: 2.0
          memory: 3G
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: host
    depends_on:
      llama-compute-node0:
        condition: service_healthy
      llama-compute-node1:
        condition: service_healthy
