FROM opensuse/tumbleweed

ENV \
    # Common settings
    FUNCTION=frontend \
    NUM_THREADS=16 \
    ## FUNCTION="compute" settings
    RPC_HOST=0.0.0.0 \
    RPC_PORT=50052 \
    RPC_CACHE=true \
    NUMA_NODE=0 \
    ## FUNCTION="frontend" settings
    MODEL_PATH=/app/models/super-model-here.ggpf \
    MODEL_CHAT_TEMPLATE= \
    RPC_SERVERS=127.0.0.1:50052 \
    CACHE_TYPE_K= \
    CACHE_TYPE_V= \
    WEB_HOST=0.0.0.0 \
    WEB_PORT=8734

ARG ZYPPER_DEPS="libgomp1-gcc7 \
                 numactl \
                 liburing2\
                "

# skip openblas-devel until fixed upstream for RPC
RUN zypper -n update && \
    zypper -n install -y ${ZYPPER_DEPS} && \
    zypper -n clean

# Copy in binaries, add to library path
COPY build/bin/ /usr/local/bin/
RUN  ldconfig /usr/local/bin

COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/llama*

WORKDIR /app

ENTRYPOINT ["entrypoint.sh"]
